task:
    name: tmate session
    timeout_in: 120m
    container:
      image: ghcr.io/popoasm/popo_docker:main
      cpu: 8
      memory: 30G
    tmate_script:
      - env
      - bash install.sh
      - bash tmate
