task:
    name: tmate session
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 2
      memory: 8G
    tmate_script:
      - env
      - sudo bash install.sh
      - bash tmate
